// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHMMXFwwBkZZyJ3ObolEbzcLyBxnDxMHY',
    appId: '1:148843099433:web:928632d3235e014f487338',
    messagingSenderId: '148843099433',
    projectId: 'arkan-989a0',
    authDomain: 'arkan-989a0.firebaseapp.com',
    storageBucket: 'arkan-989a0.appspot.com',
    measurementId: 'G-J1F3B0XQLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL4NqUpHzFZE_wVWOoDPzr4_HyEp-APk4',
    appId: '1:148843099433:android:33a6f153d1d84366487338',
    messagingSenderId: '148843099433',
    projectId: 'arkan-989a0',
    storageBucket: 'arkan-989a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNvV0ywzBcHM5dhTU4gA6UpSFiNcKKqa4',
    appId: '1:148843099433:ios:0e71e465757cfedd487338',
    messagingSenderId: '148843099433',
    projectId: 'arkan-989a0',
    storageBucket: 'arkan-989a0.appspot.com',
    iosBundleId: 'com.example.arkan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNvV0ywzBcHM5dhTU4gA6UpSFiNcKKqa4',
    appId: '1:148843099433:ios:0e71e465757cfedd487338',
    messagingSenderId: '148843099433',
    projectId: 'arkan-989a0',
    storageBucket: 'arkan-989a0.appspot.com',
    iosBundleId: 'com.example.arkan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHMMXFwwBkZZyJ3ObolEbzcLyBxnDxMHY',
    appId: '1:148843099433:web:7fa965e840e007d4487338',
    messagingSenderId: '148843099433',
    projectId: 'arkan-989a0',
    authDomain: 'arkan-989a0.firebaseapp.com',
    storageBucket: 'arkan-989a0.appspot.com',
    measurementId: 'G-RRFGL70V3X',
  );
}
